drop table VIVO_QUERY;

create table VIVO_QUERY (
        VIVO_QUERY_ID GENERATED BY DEFAULT AS IDENTITY START WITH 1000 INCREMENT BY 1,
        NAME varchar(75) null,
        QUERY_STRING varchar(1024) null
);

insert into VIVO_QUERY (NAME, QUERY_STRING) values ('Research', 'research');
insert into VIVO_QUERY (NAME, QUERY_STRING) values ('Economic', 'economic');
insert into VIVO_QUERY (NAME, QUERY_STRING) values ('Green', 'green');
